images:
  image:
    repository: jxxghp/moviepilot-v2
    tag: 2.1.7
  v1_image:
    repository: jxxghp/moviepilot
    tag: 1.9.17

consts:
  moviepilot_container_name: moviepilot
  perms_container_name: permissions
